// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using THSR.Repository.Models.Entities;

namespace THSR.Repository.Models.Context
{
    public partial class THSRContext : DbContext
    {
        public THSRContext()
        {
        }

        public THSRContext(DbContextOptions<THSRContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Fare> Fare { get; set; }
        public virtual DbSet<Station> Station { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Fare>(entity =>
            {
                entity.HasKey(e => new { e.OriginStationID, e.DestinationStationID });

                entity.Property(e => e.OriginStationID)
                    .HasMaxLength(20)
                    .HasComment("起點車站代碼");

                entity.Property(e => e.DestinationStationID)
                    .HasMaxLength(20)
                    .HasComment("迄點車站代碼");

                entity.Property(e => e.BusinessFare)
                    .HasColumnType("decimal(18, 0)")
                    .HasComment("商務車廂票價");

                entity.Property(e => e.DestinationStationName)
                    .HasMaxLength(20)
                    .HasComment("迄點車站名稱");

                entity.Property(e => e.FreeFare)
                    .HasColumnType("decimal(18, 0)")
                    .HasComment("自由座車廂票價");

                entity.Property(e => e.OriginStationName)
                    .HasMaxLength(20)
                    .HasComment("起點車站名稱 ");

                entity.Property(e => e.StandardFare)
                    .HasColumnType("decimal(18, 0)")
                    .HasComment("標準車廂票價");

                entity.Property(e => e.UpdateTime)
                    .HasColumnType("datetime")
                    .HasComment("更新時間");
            });

            modelBuilder.Entity<Station>(entity =>
            {
                entity.Property(e => e.StationID)
                    .HasMaxLength(20)
                    .HasComment("車站代碼");

                entity.Property(e => e.LocationCity)
                    .HasMaxLength(10)
                    .HasComment("車站位置所屬縣市");

                entity.Property(e => e.LocationCityCode)
                    .HasMaxLength(10)
                    .HasComment("車站位置所屬縣市代碼");

                entity.Property(e => e.LocationTown)
                    .HasMaxLength(10)
                    .HasComment("車站位置所屬鄉鎮");

                entity.Property(e => e.LocationTownCode)
                    .HasMaxLength(10)
                    .HasComment("車站位置所屬鄉鎮代碼");

                entity.Property(e => e.PositionLat).HasComment("位置緯度");

                entity.Property(e => e.PositionLon).HasComment("位置經度");

                entity.Property(e => e.StationAddress)
                    .HasMaxLength(50)
                    .HasComment("車站地址");

                entity.Property(e => e.StationCode)
                    .HasMaxLength(20)
                    .HasComment("車站簡碼(訂票系統用)");

                entity.Property(e => e.StationEnName)
                    .HasMaxLength(20)
                    .HasComment(" 車站英文名稱");

                entity.Property(e => e.StationName)
                    .HasMaxLength(20)
                    .HasComment("車站名稱");

                entity.Property(e => e.StationUID)
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasComment("車站唯一識別代碼");

                entity.Property(e => e.UpdateTime)
                    .HasColumnType("datetime")
                    .HasComment("更新時間");
            });
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}