// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using THSR.Repository.Models;

namespace THSR.Repository.Models.Context
{
    public partial class THSRContext : DbContext
    {
        public THSRContext()
        {
        }

        public THSRContext(DbContextOptions<THSRContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Station> Station { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Station>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.LocationCity)
                    .HasMaxLength(10)
                    .HasComment("車站位置所屬縣市");

                entity.Property(e => e.LocationCityCode)
                    .HasMaxLength(10)
                    .HasComment("車站位置所屬縣市代碼");

                entity.Property(e => e.LocationTown)
                    .HasMaxLength(10)
                    .HasComment("車站位置所屬鄉鎮");

                entity.Property(e => e.LocationTownCode)
                    .HasMaxLength(10)
                    .HasComment("車站位置所屬鄉鎮代碼");

                entity.Property(e => e.OperatorID)
                    .HasMaxLength(10)
                    .HasComment("營運業者代碼");

                entity.Property(e => e.PositionLat).HasComment("位置緯度");

                entity.Property(e => e.PositionLon).HasComment("位置經度");

                entity.Property(e => e.StationAddress)
                    .HasMaxLength(50)
                    .HasComment("車站地址");

                entity.Property(e => e.StationCode)
                    .HasMaxLength(20)
                    .HasComment("車站簡碼(訂票系統用)");

                entity.Property(e => e.StationEnName)
                    .HasMaxLength(20)
                    .HasComment(" 車站英文名稱");

                entity.Property(e => e.StationID)
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasComment("車站代碼");

                entity.Property(e => e.StationName)
                    .HasMaxLength(20)
                    .HasComment("車站名稱");

                entity.Property(e => e.StationUID)
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasComment("車站唯一識別代碼");

                entity.Property(e => e.UpdateTime)
                    .HasColumnType("datetime")
                    .HasComment("本平台資料更新時間");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}