// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace THSR.Repository.Models.Entities
{
    public partial class Fare
    {
        /// <summary>
        /// 起點車站代碼
        /// </summary>
        public string OriginStationID { get; set; }
        /// <summary>
        /// 起點車站名稱 
        /// </summary>
        public string OriginStationName { get; set; }
        /// <summary>
        /// 迄點車站代碼
        /// </summary>
        public string DestinationStationID { get; set; }
        /// <summary>
        /// 迄點車站名稱
        /// </summary>
        public string DestinationStationName { get; set; }
        /// <summary>
        /// 商務車廂票價
        /// </summary>
        public decimal? BusinessFare { get; set; }
        /// <summary>
        /// 自由座車廂票價
        /// </summary>
        public decimal? FreeFare { get; set; }
        /// <summary>
        /// 標準車廂票價
        /// </summary>
        public decimal? StandardFare { get; set; }
        /// <summary>
        /// 更新時間
        /// </summary>
        public DateTime? UpdateTime { get; set; }
    }
}