// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace THSR.Repository.Models
{
    public partial class GeneralTimetable
    {
        public GeneralTimetable()
        {
            RailStopTime = new HashSet<RailStopTime>();
        }

        /// <summary>
        /// 車次代碼
        /// </summary>
        public string TrainNo { get; set; }
        /// <summary>
        /// 行駛方向 : [0:&apos;南下&apos;,1:&apos;北上&apos;] 
        /// </summary>
        public bool? Direction { get; set; }
        /// <summary>
        ///  列車起點車站代號
        /// </summary>
        public string StartingStationID { get; set; }
        /// <summary>
        /// 列車終點車站代號 
        /// </summary>
        public string EndingStationID { get; set; }
        /// <summary>
        /// 星期一是否營運
        /// </summary>
        public bool? ServiceMonday { get; set; }
        /// <summary>
        /// 星期二是否營運
        /// </summary>
        public bool? ServiceTuesday { get; set; }
        /// <summary>
        /// 星期三是否營運
        /// </summary>
        public bool? ServiceWednesday { get; set; }
        /// <summary>
        /// 星期四是否營運
        /// </summary>
        public bool? ServiceThursday { get; set; }
        /// <summary>
        /// 星期五是否營運
        /// </summary>
        public bool? ServiceFriday { get; set; }
        /// <summary>
        /// 星期六是否營運
        /// </summary>
        public bool? ServiceSaturday { get; set; }
        /// <summary>
        /// 星期日是否營運
        /// </summary>
        public bool? ServiceSunday { get; set; }
        /// <summary>
        /// 資料更新時間
        /// </summary>
        public DateTime? UpdateTime { get; set; }

        public virtual ICollection<RailStopTime> RailStopTime { get; set; }
    }
}