// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace THSR.Repository.Models.Entities
{
    public partial class Station
    {
        /// <summary>
        /// 車站代碼
        /// </summary>
        public string StationID { get; set; }
        /// <summary>
        /// 車站唯一識別代碼
        /// </summary>
        public string StationUID { get; set; }
        /// <summary>
        /// 車站簡碼(訂票系統用)
        /// </summary>
        public string StationCode { get; set; }
        /// <summary>
        /// 車站名稱
        /// </summary>
        public string StationName { get; set; }
        /// <summary>
        ///  車站英文名稱
        /// </summary>
        public string StationEnName { get; set; }
        /// <summary>
        /// 車站地址
        /// </summary>
        public string StationAddress { get; set; }
        /// <summary>
        /// 位置緯度
        /// </summary>
        public double PositionLat { get; set; }
        /// <summary>
        /// 位置經度
        /// </summary>
        public double PositionLon { get; set; }
        /// <summary>
        /// 車站位置所屬縣市
        /// </summary>
        public string LocationCity { get; set; }
        /// <summary>
        /// 車站位置所屬縣市代碼
        /// </summary>
        public string LocationCityCode { get; set; }
        /// <summary>
        /// 車站位置所屬鄉鎮
        /// </summary>
        public string LocationTown { get; set; }
        /// <summary>
        /// 車站位置所屬鄉鎮代碼
        /// </summary>
        public string LocationTownCode { get; set; }
        /// <summary>
        /// 更新時間
        /// </summary>
        public DateTime? UpdateTime { get; set; }
    }
}